from enum import StrEnum


class ReadinessStatus(StrEnum):
    READY_TO_EVALUATE = "READY_TO_EVALUATE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    ELIGIBILITY_BLOCKED = "ELIGIBILITY_BLOCKED"
    DEADLINE_PASSED = "DEADLINE_PASSED"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"


class FeasibilityStatus(StrEnum):
    FEASIBLE = "FEASIBLE"
    FEASIBLE_WITH_TRADEOFFS = "FEASIBLE_WITH_TRADEOFFS"
    TIGHT_CAPACITY = "TIGHT_CAPACITY"
    NOT_FEASIBLE_UNDER_CURRENT_CONSTRAINTS = "NOT_FEASIBLE_UNDER_CURRENT_CONSTRAINTS"


class CommitmentType(StrEnum):
    FIXED = "FIXED"
    FLEXIBLE = "FLEXIBLE"


class CanonicalFieldState(StrEnum):
    VERIFIED = "VERIFIED"
    SINGLE_SOURCE = "SINGLE_SOURCE"
    CONFLICT = "CONFLICT"
    MISSING = "MISSING"
    UNVERIFIED = "UNVERIFIED"


class RecommendationAction(StrEnum):
    ACCEPT = "ACCEPT"
    CHOOSE_ALTERNATIVE = "CHOOSE_ALTERNATIVE"
    EDIT_CONSTRAINTS = "EDIT_CONSTRAINTS"
    IGNORE = "IGNORE"
